version: "3"
services:
  my-web-app-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydatabase
  my-web-app:
    build: .
    ports:
      - "5438:5432"
    depends_on:
      - my-web-app-db
